<a href="https://colab.research.google.com/github/Abhishekgusain123/ma22c003_2023_PL/blob/main/Column_Space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task:1-You have seen that the SVD of an m × n matrix A gives, among other things, a
basis for the range (column space). Compute this for the given matrix.
Another way to obtain a basis for the range is using the QR factorization, also implemented
in scipy. Carefully go through the linked QR documentation page. Then compute a basis
for the column space of a given A using QR, and then using the SVD.

In [22]:
import numpy as np

# Define matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the SVD of matrix A
U, S, Vt = np.linalg.svd(A)

# The basis for the column space is given by the columns of U
column_space_basis = U

print("Basis for the column space using SVD:")
print(column_space_basis)

Basis for the column space using SVD:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


In [25]:

import numpy as np
from scipy.linalg import qr, svd

# Compute a basis for the column space using QR factorization
Q, _ = qr(A, mode='economic')
column_space_basis_qr = Q

# Compute a basis for the column space using SVD
U, _, _ = svd(A)
column_space_basis_svd = U

print("Basis for the column space using QR:")
print(column_space_basis_qr)

print("\nBasis for the column space using SVD:")
print(column_space_basis_svd)

Basis for the column space using QR:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

Basis for the column space using SVD:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]


Task 2: Check that the column spaces (not the bases) you obtained in the two ways are the
same. (How would you check that two given bases span the same space?)

In [20]:

# Basis of column space using QR factorization
Q, _ = qr(A, mode='economic')

# Basis of column space using SVD
U, _, _ = svd(A)

# if the dimensions of the column spaces are the same
if Q.shape[1] == U.shape[1]:
    print("Dimensions of column spaces are the same.")

# if the column spaces have the same subspace spanned by the basis vectors
if np.allclose(np.dot(A, Q), np.dot(A, U)):
    print("Column spaces are the same.")
else:
    print("Column spaces are different.")

Dimensions of column spaces are the same.
Column spaces are different.


Task 3: For a 500 × 500 random matrix, which method is faster?

In [21]:

import numpy as np
from scipy.linalg import qr, svd
import timeit

# Compute a random 500x500 matrix
np.random.seed(0)  # for reproducibility
A = np.random.rand(500, 500)

# Timing for QR factorization
qr_time = timeit.timeit(lambda: qr(A, mode='economic'), number=100)

# Timing for SVD
svd_time = timeit.timeit(lambda: svd(A), number=100)

print(f"Time taken for QR factorization: {qr_time:.4f} seconds")
print(f"Time taken for SVD: {svd_time:4f} seconds")

if qr_time < svd_time:
    print("QR factorization is faster.")
else:
    print("SVD is faster.")

Time taken for QR factorization: 3.5001 seconds
Time taken for SVD: 14.093415 seconds
QR factorization is faster.
