<a href="https://colab.research.google.com/github/Abhishekgusain123/ma22c003_2023_PL/blob/main/Pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.random.rand(5) #generates a 1D NumPy array x of length 5 with random numbers between 0 and 1.
D = np.subtract.outer(x, x) #calculates the pairwise differences between elements of x
print(D)

[[ 0.         -0.03249166  0.14289295  0.1361538   0.79688184]
 [ 0.03249166  0.          0.17538461  0.16864546  0.82937351]
 [-0.14289295 -0.17538461  0.         -0.00673916  0.65398889]
 [-0.1361538  -0.16864546  0.00673916  0.          0.66072805]
 [-0.79688184 -0.82937351 -0.65398889 -0.66072805  0.        ]]


In [ ]:
import numpy as np

A = np.subtract.outer(x, x)
print(A)

[[ 0.         -0.03249166  0.14289295  0.1361538   0.79688184]
 [ 0.03249166  0.          0.17538461  0.16864546  0.82937351]
 [-0.14289295 -0.17538461  0.         -0.00673916  0.65398889]
 [-0.1361538  -0.16864546  0.00673916  0.          0.66072805]
 [-0.79688184 -0.82937351 -0.65398889 -0.66072805  0.        ]]
