In [1]:
import numpy as np

def swaprow(i, j, A): #The swaprow function is defined to swap two rows i ,j and A is the input matrix.
    tmp = A[i, :]# Store the 'i'th row of matrix A in a temporary variable 'tmp'
    A[i, :] = A[j, :] #we replace the values of row i with the values of row j.
    A[j, :] = tmp  # Replace the 'j'th row of A with the original ith row stored in tmp
    return A
    print(id(tmp))
    print(id( A[j, :]))
    print(id( A[i, :]))


# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Call swaprow() to interchange rows 0 and 2 (first and last rows)
swaprow(0, 2, A)

# Print the updated matrix A
print(A)



[[7 8 9]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

def new_swaprows(i, j, A):
    A[[i, j]] = A[[j, i]] #Swapping row 'i' and 'j'.

# Example,now we consider a 3*3 matrix:
A = np.array([[1, 2, 3],
             [4, 5, 6],
            [7, 8, 9]])
print("Original array:")
print(A)

new_swaprows(0,2 , A) #Swaping row '0' and row '2':
print("\nArray after swapping rows 0 and 2:")
print(A)


Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping rows 0 and 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]



#This implementation directly swaps the rows i and j without using a temporary variable, making it more efficient.
# It's also more concise and easier to read.

